branch-defaults:
  master:
    environment: peoplefinder-dev
global:
  application_name: peoplefinder-2.0
  branch: null
  default_ec2_keyname: pf
  default_platform: Ruby 2.3 (Puma)
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
